export const dashboardStyles = {
  container: {
    flex: 1,
    backgroundColor: '#f4f7fa',
  },
  scroll: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 10,
  },
  headerCard: {
    position: 'relative',
    backgroundColor: '#1E90FF',
    borderRadius: 18,
    marginBottom: 18,
    // marginTop: 40,
    elevation: 4,
    shadowColor: '#1E90FF',
    shadowOpacity: 0.11,
    shadowRadius: 12,
    shadowOffset: {width: 0, height: 3},
    padding: 22, // <-- lebih besar
    minHeight: 132,
  },
  headerText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 2,
  },
  logoutIconBtn: {
    position: 'absolute',
    right: 18,
    top: 18,
    padding: 8,
    borderRadius: 99,
    backgroundColor: 'rgba(255,255,255,0.15)',
    zIndex: 10,
  },
  userCard: {
    marginTop: 28,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 14,
    padding: 12,
  },
  name: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  info: {
    color: '#fff',
    fontSize: 13,
    marginTop: 1,
  },
  // Menu horizontal card
  menuCard: {
    backgroundColor: '#fff',
    marginRight: 14,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 22,
    alignItems: 'center',
    flexDirection: 'row',
    minWidth: 130,
    elevation: 2,
    shadowColor: '#1E90FF',
    shadowOpacity: 0.13,
    shadowRadius: 7,
    shadowOffset: {width: 0, height: 2},
  },
  menuCardActive: {
    backgroundColor: '#e6f2ff',
    borderColor: '#1E90FF',
    borderWidth: 1.3,
  },
  menuCardText: {
    marginLeft: 12,
    fontWeight: '600',
    color: '#1E90FF',
    fontSize: 16,
    flex: 1,
  },
  // Subsubmenu grid
  subGridCard: {
    flex: 1,
    backgroundColor: '#fff',
    margin: 8,
    paddingVertical: 22,
    borderRadius: 18,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.09,
    shadowRadius: 7,
    shadowOffset: {width: 0, height: 2},
  },
  subGridText: {
    marginTop: 12,
    fontWeight: '700',
    color: '#1E90FF',
    fontSize: 15,
    textAlign: 'center',
  },
  // Bottom navigation bar
  bottomMenuBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 8,
    paddingVertical: 10,
    zIndex: 99,
  },
  bottomMenuItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    marginHorizontal: 4,
    borderRadius: 14,
    backgroundColor: 'transparent',
  },
  bottomMenuItemSelected: {
    backgroundColor: '#1E90FF',
  },
  bottomMenuText: {
    fontSize: 12,
    color: '#1E90FF',
    marginTop: 2,
    fontWeight: '600',
  },
  summaryCardInteractive: {
    width: 142,
    backgroundColor: '#1E90FF',
    borderRadius: 16,
    padding: 18,
    marginRight: 15,
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#222',
    shadowOpacity: 0.11,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 4},
  },
  summaryLabel: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 5,
  },
  summaryValue: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 25,
    marginTop: 1,
  },
  summarySub: {
    color: '#fff',
    fontSize: 12,
    marginTop: 4,
    opacity: 0.86,
  },
  statusContainer: {
    alignItems: 'flex-end',
  },
  statusIndicator: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
    fontWeight: 'bold',
    fontSize: 13,
    marginBottom: 2,
  },
  statusOnline: {
    backgroundColor: '#d4edda',
    color: '#155724',
  },
  statusOffline: {
    backgroundColor: '#f8d7da',
    color: '#721c24',
  },
  statusTime: {
    fontSize: 12,
    color: '#555',
    fontWeight: '500',
  },
  pushQueueBadge: {
    backgroundColor: '#e74c3c',
    margin: 14,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
  },
  pushQueueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 7,
  },
  pushQueueText: {
    color: '#fff',
    flex: 1,
  },
  pushQueueButton: {
    backgroundColor: '#27ae60',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    marginLeft: 10,
  },
  pushQueueButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  headerWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginTop: 16,
    marginBottom: 6,
    justifyContent: 'space-between',
  },
  logo: {
    width: 110,
    height: 55,
    resizeMode: 'contain',
  },
  forceUpdateWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  forceUpdateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1976d2',
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 12,
    marginRight: 6,
  },
  forceUpdateButtonDisabled: {
    opacity: 0.6,
  },
  forceUpdateButtonText: {
    color: '#fff',
    marginLeft: 5,
    fontWeight: 'bold',
    fontSize: 13,
  },
  forceUpdateStatus: {
    fontSize: 11,
    color: '#1976d2',
    fontWeight: 'bold',
  },
  modalBackground: {
    flex: 1,
    backgroundColor: '#0008',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 24,
    alignItems: 'center',
    width: 260,
  },
  modalTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 13,
  },
  modalProgressText: {
    marginTop: 8,
    fontSize: 14,
  },
  modalDesc: {
    fontSize: 12,
    color: '#555',
    marginTop: 6,
  },
  progressBar: {
    width: 180,
  },
  subsubmenuGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingBottom: 8,
  },
  menuListContainer: {
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  summaryCardScroll: {
    paddingLeft: 14,
    paddingBottom: 6,
  },
};
