export const tabelStyles = {
  pageTitle: {
    fontSize: 21,
    fontWeight: 'bold',
    color: '#1E90FF',
    marginBottom: 16,
    alignSelf: 'center',
  },
  searchInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 11,
    marginBottom: 14,
    fontSize: 15,
    borderColor: '#e6e8ec',
    borderWidth: 1,
  },
  pickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginLeft: 4,
  },
  pickerLabel: {
    fontWeight: '600',
    color: '#1E90FF',
    marginRight: 8,
    fontSize: 15,
  },
  pickerWrapper: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 4,
    borderColor: '#e6e8ec',
    borderWidth: 1,
    minWidth: 65,
  },
  picker: {
    color: '#1E90FF',
    fontSize: 15,
    paddingVertical: 5,
    textAlign: 'center',
  },
  cardContainer: {
    backgroundColor: '#fff',
    borderRadius: 18,
    marginVertical: 7,
    marginHorizontal: 6,
    padding: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 2},
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#1E90FF',
  },
  cardSubtitle: {
    color: '#888',
    marginTop: 2,
    fontSize: 15,
  },
  cardSite: {
    color: '#F39C12',
    fontWeight: 'bold',
    fontSize: 14,
  },
  cardDetail: {
    marginTop: 16,
  },
  cardDetailText: {
    fontSize: 14,
    color: '#333',
    marginBottom: 3,
  },
  cardActionRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 14,
  },
  editButton: {
    backgroundColor: '#1E90FF',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginRight: 10,
  },
  deleteButton: {
    backgroundColor: '#FF3B30',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  actionButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  cardExpanded: {
    backgroundColor: '#f1f8ff',
    borderColor: '#1E90FF',
    borderWidth: 1,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 10,
  },
  pageButton: {
    backgroundColor: '#1E90FF',
    paddingVertical: 8,
    paddingHorizontal: 18,
    borderRadius: 12,
    marginHorizontal: 8,
  },
  pageButtonDisabled: {
    backgroundColor: '#b0c4de',
  },
  pageButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  pageInfo: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#1E90FF',
    marginHorizontal: 10,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardSectionTitle: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#1E90FF',
    marginTop: 2,
    marginBottom: 2,
    letterSpacing: 0.2,
  },
};
